name: payze
description: "A new Flutter project."
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/payze.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  plugin:
    platforms:
      android:
        package: uz.udevs.payze
        pluginClass: PayzePlugin
      ios:
        pluginClass: PayzePlugin
